config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'new'     => 'users#new'
  get 'play'    => 'game#play'
  post 'play'   => 'game#resolve'
  get 'hall'    => 'hall#show'
  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
    
    validates :name, presence: true, length: {maximum: 30 }
    validates :points, presence: true
    validates :longest_streak, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
   include UsersHelper
   include GameHelper
    
    respond_to :html, :js
    
    def play
    end
    
    
    def resolve
        if params[:chosen] == 'game_over'
            session[:lives] = 0
        else
            @computer_choice = $VAR_HANDS.sample
            @winning_hand = $RULES[params[:chosen].to_sym][@computer_choice.to_sym]
            calc_game_status(claim_winner)
        end
        respond_to do |format|
            if game_over?
            #clear session, save score in database and render summary page
                @user = User.new(name: session[:user_name], points: session[:user_points], longest_streak: session[:user_longest_streak])
                @user.save
                session.clear
                format.js { render :partial => "shared/game_over.js"}
            else
                format.js { render :partial => "shared/update.js"}
            end
        end
    end
    
end

app/controllers/hall_controller.rb
class HallController < ApplicationController
    
    def show
        @users_by_points = User.order(points: :desc).all
        @users_by_streak = User.order(longest_streak: :desc).all
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  include UsersHelper
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
      @user = User.new(name: params[:user][:name], points: 0, longest_streak: 0)
      if @user.validate
        log_in @user
        redirect_to play_path
      else
        render 'new'
      end

  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = '')
        base_title = "RPSSL by Mateusz Gołosz"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
    
end

app/helpers/game_helper.rb
module GameHelper
    
    $VAR_HANDS = %w[spock scissors lizard rock paper]
    $RULES =  {
            :rock     => {:rock => :draw, :paper => :paper, :scissors => :rock, :lizard => :rock, :spock => :spock},
            :paper    => {:rock => :paper, :paper => :draw, :scissors => :scissors, :lizard => :lizard, :spock => :paper},
            :scissors => {:rock => :rock, :paper => :scissors, :scissors => :draw, :lizard => :scissors, :spock => :spock},
            :spock    => {:rock => :spock, :paper => :paper, :scissors => :spock, :lizard => :lizard, :spock => :draw},
            :lizard   => {:rock => :rock, :paper => :lizard, :scissors => :scissors, :lizard => :draw, :spock => :lizard}
        }
        
    def calc_game_status (winner)
        case winner
            when :computer
                session[:lives] -= 1
                session[:user_current_streak] = 0
            when :player
                session[:user_points] += 1
                session[:user_current_streak] += 1
                if session[:user_current_streak] > session[:user_longest_streak]
                    session[:user_longest_streak] = session[:user_current_streak]
                end
        end
    end
    
    def game_over?
        case session[:lives]
            when 0 then true
            else false
        end
    end
    
    def claim_winner
        @winner = case @winning_hand
            when @computer_choice.to_sym then :computer
            when :draw then :draw
            else :player
        end
    end
    
end

app/helpers/hall_helper.rb
module HallHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def log_in(user)
        session[:user_id] = user.id
        session[:user_name] = user.name
        session[:user_points] = user.points
        session[:user_longest_streak] = user.longest_streak
        session[:lives] = 3;
        session[:user_current_streak] = 0
    end
  
    def logged_in?
        !session[:user_name].nil?
    end
  
end

app/views/game/play.html.erb
<% provide(:title, 'Play') %>
<% if logged_in? %>
<h1><%= session[:user_name] %></h1>
<div class='main'>
    <h4>Score: <%= session[:user_points] %></h4>
    <h4>Longest streak: <%= session[:user_longest_streak] %></h4>
    <h4>Lives left: <%= session[:lives] %></h4>
</div>
<div align="center">
    <% $VAR_HANDS.each do |element| %>
    <%= link_to image_tag(element.to_s + ".png", class: 'image-responsive'), play_path(chosen: element), method: 'post', remote: true %>
    <% end %>
    <div><%= link_to "End game", play_path(chosen: 'game_over'), method: 'post', remote: true, class: "endbtn btn btn-lg btn-default" %></div>
</div>
    <% else %>
    <h1>You have to pick your name first.</h1>
    <h4>Redirecting to homepage in 5s.</h4>
    <meta HTTP-EQUIV="REFRESH" content="5; <%= root_path %>">
<% end %>

app/views/hall/show.html.erb
<% provide(:title, 'Hall of Fame') %>
<div id='tablewrap'>
    <table style="width:35%" class='pointstable'>
        <col width="70%">
        <col width="30%">
        <caption>Players by points</caption>
            <tr>
                <th style="text-align:center">Name</th>
                <th style="text-align:center">Score</th>
            </tr>
            <% @users_by_points.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.points.to_s %></td> 
            </tr>
            <% end %>
    </table>
    <table style="width:35%" class='streaktable'>
        <col width="70%">
        <col width="30%">
        <caption>Players by streak</caption>
            <tr>
                <th style="text-align:center">Name</th>
                <th style="text-align:center">Longest streak</th>
            </tr>
            <% @users_by_streak.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td align="center"><%= user.longest_streak.to_s %></td> 
            </tr>
            <% end %>
    </table>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The RPSSL game by Mateusz Gołosz
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_game_over.js.erb
$('.main').replaceWith("<%= escape_javascript render(:partial => 'shared/summary') %>");
$('.image-responsive').remove();
$('.endbtn').remove();

app/views/shared/_summary.html.erb
<h1>Game over.</h1>
<h2>Points: <%= @user.points %></h2>
<h2>Longest streak: <%= @user.longest_streak %></h2>
<div class="center sumbtn">
  <div><%= link_to "New Game", new_path, class: "btn btn-lg btn-primary" %></div>
  <div><%= link_to "Hall of Fame", hall_path, class: "btn btn-lg btn-primary" %></div>
</div>

app/views/shared/_update.js.erb
$('.main').replaceWith("<%= escape_javascript render(:partial => 'shared/updated_values') %>");

app/views/shared/_updated_values.html.erb
<div class='main'>
    <div class='player'>
        <h2>You <%= "win" if @winner == :player %></h2>
        <div><%= image_tag(params[:chosen].to_s, alt: "Player hand image", class: 'vsimg')%></div>
    </div>
    <div class='computer'>
        <h2>Computer <%= "wins" if @winner == :computer %></h2>
        <div><%= image_tag(@computer_choice.to_s, alt: "Computer hand image", class: 'vsimg', id: 'compimg')%></div>
    </div>
    <div class='score'>
        <h4>Score: <%= session[:user_points] %></h4>
        <h4>Longest streak: <%= session[:user_longest_streak] %></h4>
        <h4>Lives left: <%= session[:lives] %></h4>
    </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center">
    <p>Exclusively for The Software House</p>
    <p>All game related images taken from <%= link_to "picoplex.net", "http://picoplex.net" %></p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1><%= mail_to "matgolosz@gmail.com", "matgolosz@gmail.com" %></h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center">
    <p>Player chooses one of the gestures by clicking on its icon.</p>
    <p>The way gestures beat each other is visualised below.</p>
    <p><%= image_tag("rules.png", alt: "rules")%></p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>RPSSL</h1>
  <div><%= link_to "New Game", new_path, class: "btn btn-lg btn-primary" %></div>
  <div><%= link_to "Hall of Fame", hall_path, class: "btn btn-lg btn-primary" %></div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Pick your nickname') %>
<h1>Pick your nickname</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit "Play", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>